"""Core event system for Krator trading platform.

This module defines all event types used throughout the system, ensuring proper
dataclass field ordering (non-default fields first) to prevent common bugs.
"""

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Optional, Dict, Any, List
from uuid import UUID, uuid4


class EventType(Enum):
    """Event type enumeration for system events."""
    # Market data events
    MARKET_DATA_RECEIVED = "market_data_received"
    PRICE_UPDATE = "price_update"
    ORDER_BOOK_UPDATE = "order_book_update"
    
    # Strategy events
    SIGNAL_GENERATED = "signal_generated"
    STRATEGY_STATE_CHANGED = "strategy_state_changed"
    
    # Trading events
    ORDER_SUBMITTED = "order_submitted"
    ORDER_FILLED = "order_filled"
    ORDER_PARTIAL_FILL = "order_partial_fill"
    ORDER_CANCELLED = "order_cancelled"
    ORDER_REJECTED = "order_rejected"
    
    # Portfolio events
    POSITION_OPENED = "position_opened"
    POSITION_CLOSED = "position_closed"
    POSITION_UPDATED = "position_updated"
    PORTFOLIO_UPDATED = "portfolio_updated"
    
    # Risk events
    RISK_LIMIT_BREACH = "risk_limit_breach"
    CIRCUIT_BREAKER_TRIGGERED = "circuit_breaker_triggered"
    DRAWDOWN_ALERT = "drawdown_alert"
    
    # System events
    SYSTEM_STARTUP = "system_startup"
    SYSTEM_SHUTDOWN = "system_shutdown"
    HEARTBEAT = "heartbeat"
    ERROR_OCCURRED = "error_occurred"
    RECOVERY_COMPLETED = "recovery_completed"


class OrderSide(Enum):
    """Order side enumeration."""
    BUY = "BUY"
    SELL = "SELL"


class OrderType(Enum):
    """Order type enumeration."""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class OrderStatus(Enum):
    """Order status enumeration."""
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    PARTIAL_FILLED = "PARTIAL_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


@dataclass(frozen=True)
class BaseEvent:
    """Base event class with common fields."""
    event_id: UUID
    event_type: EventType
    timestamp: datetime
    source: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Validate event data after initialization."""
        if not isinstance(self.event_id, UUID):
            raise ValueError("event_id must be a UUID")
        if not isinstance(self.timestamp, datetime):
            raise ValueError("timestamp must be a datetime")


@dataclass(frozen=True)
class MarketDataEvent(BaseEvent):
    """Market data update event."""
    symbol: str
    price: Decimal
    volume: int
    exchange: str
    bid: Optional[Decimal] = None
    ask: Optional[Decimal] = None
    bid_size: Optional[int] = None
    ask_size: Optional[int] = None


@dataclass(frozen=True)
class PriceUpdateEvent(BaseEvent):
    """Price update event for OHLCV data."""
    symbol: str
    open_price: Decimal
    high_price: Decimal
    low_price: Decimal
    close_price: Decimal
    volume: int
    timeframe: str
    exchange: str = "ALPACA"


@dataclass(frozen=True)
class SignalEvent(BaseEvent):
    """Trading signal event generated by strategies."""
    symbol: str
    signal_type: str
    side: OrderSide
    strength: float
    strategy_name: str
    target_price: Optional[Decimal] = None
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    confidence: float = 0.0
    indicators: Dict[str, float] = field(default_factory=dict)


@dataclass(frozen=True)
class OrderEvent(BaseEvent):
    """Order-related event."""
    order_id: str
    symbol: str
    side: OrderSide
    order_type: OrderType
    quantity: int
    price: Optional[Decimal] = None
    stop_price: Optional[Decimal] = None
    status: OrderStatus = OrderStatus.PENDING
    filled_quantity: int = 0
    avg_fill_price: Optional[Decimal] = None
    commission: Decimal = Decimal('0')
    client_order_id: Optional[str] = None
    reject_reason: Optional[str] = None


@dataclass(frozen=True)
class FillEvent(BaseEvent):
    """Order fill event."""
    order_id: str
    symbol: str
    side: OrderSide
    fill_quantity: int
    fill_price: Decimal
    commission: Decimal
    execution_id: str
    remaining_quantity: int = 0
    total_filled: int = 0
    is_complete: bool = False


@dataclass(frozen=True)
class PositionEvent(BaseEvent):
    """Position update event."""
    symbol: str
    quantity: int
    avg_price: Decimal
    market_value: Decimal
    unrealized_pnl: Decimal
    realized_pnl: Decimal = Decimal('0')
    side: str = "LONG"  # LONG or SHORT


@dataclass(frozen=True)
class PortfolioEvent(BaseEvent):
    """Portfolio update event."""
    total_value: Decimal
    cash: Decimal
    buying_power: Decimal
    equity: Decimal
    unrealized_pnl: Decimal
    realized_pnl: Decimal
    day_trade_count: int = 0
    positions_count: int = 0


@dataclass(frozen=True)
class RiskEvent(BaseEvent):
    """Risk management event."""
    risk_type: str
    severity: str
    message: str
    symbol: Optional[str] = None
    current_value: Optional[float] = None
    threshold_value: Optional[float] = None
    action_taken: Optional[str] = None


@dataclass(frozen=True)
class SystemEvent(BaseEvent):
    """System-level event."""
    component: str
    status: str
    message: str
    details: Dict[str, Any] = field(default_factory=dict)
    error_code: Optional[str] = None
    stack_trace: Optional[str] = None


@dataclass(frozen=True)
class HealthCheckEvent(BaseEvent):
    """Health check event for system monitoring."""
    component: str
    status: str
    response_time_ms: float
    details: Dict[str, Any] = field(default_factory=dict)
    is_healthy: bool = True


# Event factory functions for easier creation

def create_market_data_event(
    symbol: str,
    price: Decimal,
    volume: int,
    exchange: str = "ALPACA",
    source: str = "market_data_feed",
    **kwargs
) -> MarketDataEvent:
    """Create a market data event with default values."""
    return MarketDataEvent(
        event_id=uuid4(),
        event_type=EventType.MARKET_DATA_RECEIVED,
        timestamp=datetime.utcnow(),
        source=source,
        symbol=symbol,
        price=price,
        volume=volume,
        exchange=exchange,
        **kwargs
    )


def create_signal_event(
    symbol: str,
    signal_type: str,
    side: OrderSide,
    strength: float,
    strategy_name: str,
    source: str = "strategy_engine",
    **kwargs
) -> SignalEvent:
    """Create a trading signal event with default values."""
    return SignalEvent(
        event_id=uuid4(),
        event_type=EventType.SIGNAL_GENERATED,
        timestamp=datetime.utcnow(),
        source=source,
        symbol=symbol,
        signal_type=signal_type,
        side=side,
        strength=strength,
        strategy_name=strategy_name,
        **kwargs
    )


def create_order_event(
    order_id: str,
    symbol: str,
    side: OrderSide,
    order_type: OrderType,
    quantity: int,
    source: str = "order_manager",
    **kwargs
) -> OrderEvent:
    """Create an order event with default values."""
    return OrderEvent(
        event_id=uuid4(),
        event_type=EventType.ORDER_SUBMITTED,
        timestamp=datetime.utcnow(),
        source=source,
        order_id=order_id,
        symbol=symbol,
        side=side,
        order_type=order_type,
        quantity=quantity,
        **kwargs
    )


def create_system_event(
    component: str,
    status: str,
    message: str,
    event_type: EventType = EventType.SYSTEM_STARTUP,
    source: str = "system",
    **kwargs
) -> SystemEvent:
    """Create a system event with default values."""
    return SystemEvent(
        event_id=uuid4(),
        event_type=event_type,
        timestamp=datetime.utcnow(),
        source=source,
        component=component,
        status=status,
        message=message,
        **kwargs
    )
